import { IPedra } from './domino.interface';

export const pedrasFactory = (): IPedra[] => [
  { valor1: 0, valor2: 0, invertido: false },
  { valor1: 0, valor2: 1, invertido: false },
  { valor1: 0, valor2: 2, invertido: false },
  { valor1: 0, valor2: 3, invertido: false },
  { valor1: 0, valor2: 4, invertido: false },
  { valor1: 0, valor2: 5, invertido: false },
  { valor1: 0, valor2: 6, invertido: false },
  { valor1: 1, valor2: 1, invertido: false },
  { valor1: 1, valor2: 2, invertido: false },
  { valor1: 1, valor2: 3, invertido: false },
  { valor1: 1, valor2: 4, invertido: false },
  { valor1: 1, valor2: 5, invertido: false },
  { valor1: 1, valor2: 6, invertido: false },
  { valor1: 2, valor2: 2, invertido: false },
  { valor1: 2, valor2: 3, invertido: false },
  { valor1: 2, valor2: 4, invertido: false },
  { valor1: 2, valor2: 5, invertido: false },
  { valor1: 2, valor2: 6, invertido: false },
  { valor1: 3, valor2: 3, invertido: false },
  { valor1: 3, valor2: 4, invertido: false },
  { valor1: 3, valor2: 5, invertido: false },
  { valor1: 3, valor2: 6, invertido: false },
  { valor1: 4, valor2: 4, invertido: false },
  { valor1: 4, valor2: 5, invertido: false },
  { valor1: 4, valor2: 6, invertido: false },
  { valor1: 5, valor2: 5, invertido: false },
  { valor1: 5, valor2: 6, invertido: false },
  { valor1: 6, valor2: 6, invertido: false },
];
